name: docker-build
on:
  workflow_dispatch:

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: asia-south1-docker.pkg.dev/density-dev-app-layer/density-dev-artifact-registry/cloudproxy
          username: _json_key
          password: ${{ secrets.DENSITY_DEV_GITHUB_GAR_SA }}
      - name: Set Image Tag
        id: set-image-tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Docker build & push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            asia-south1-docker.pkg.dev/density-dev-app-layer/density-dev-artifact-registry/cloudproxy:${{ steps.set-image-tag.outputs.sha_short }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

